//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAdminData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.RouteStopTmps = new HashSet<RouteStopTmp>();
            this.RouteStops = new HashSet<RouteStop>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public double Lon { get; set; }
        public double Lat { get; set; }
        public string Name { get; set; }
        public int SystemId { get; set; }
        public System.Data.Spatial.DbGeography Geo { get; set; }
        public double RadMeters { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string LocationType { get; set; }
    
        public virtual TransitSystem TransitSystem { get; set; }
        public virtual ICollection<RouteStopTmp> RouteStopTmps { get; set; }
        public virtual ICollection<RouteStop> RouteStops { get; set; }
    }
}
