//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAdminData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteStopTmp
    {
        public int Id { get; set; }
        public int RouteId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public double Lon { get; set; }
        public double Lat { get; set; }
        public string Name { get; set; }
        public System.Data.Spatial.DbGeography Geo { get; set; }
        public Nullable<int> MatchedLocationId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual RouteTmp RouteTmp { get; set; }
    }
}
