//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAdminData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteVariant
    {
        public RouteVariant()
        {
            this.RouteStops = new HashSet<RouteStop>();
            this.TripTemplates = new HashSet<TripTemplate>();
        }
    
        public int Id { get; set; }
        public int RouteId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual ICollection<RouteStop> RouteStops { get; set; }
        public virtual ICollection<TripTemplate> TripTemplates { get; set; }
    }
}
