//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAdminData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransitSystem
    {
        public TransitSystem()
        {
            this.Locations = new HashSet<Location>();
            this.TransitServices = new HashSet<TransitService>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<TransitService> TransitServices { get; set; }
    }
}
