//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAdminData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransitService
    {
        public TransitService()
        {
            this.Routes = new HashSet<Route>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int Id { get; set; }
        public int SystemId { get; set; }
        public string SystemType { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Route> Routes { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual TransitSystem TransitSystem { get; set; }
    }
}
