//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAdminData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripTemplateStop
    {
        public int Id { get; set; }
        public int TripTemplateId { get; set; }
        public int RouteStopId { get; set; }
        public int StopOrder { get; set; }
        public int SecondsFromPrevious { get; set; }
    
        public virtual RouteStop RouteStop { get; set; }
        public virtual TripTemplate TripTemplate { get; set; }
    }
}
