//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAdminData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripTemplate
    {
        public TripTemplate()
        {
            this.TripTemplateStops = new HashSet<TripTemplateStop>();
        }
    
        public int Id { get; set; }
        public int RouteVariantId { get; set; }
        public byte WeekDays { get; set; }
        public string TripId { get; set; }
        public string TripName { get; set; }
    
        public virtual RouteVariant RouteVariant { get; set; }
        public virtual ICollection<TripTemplateStop> TripTemplateStops { get; set; }
    }
}
