//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTAdminData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UptRTEntities : DbContext
    {
        public UptRTEntities()
            : base("name=UptRTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Location> Locations { get; set; }
        public DbSet<Route> Routes { get; set; }
        public DbSet<RouteStop> RouteStops { get; set; }
        public DbSet<RouteStopTmp> RouteStopTmps { get; set; }
        public DbSet<RouteTmp> RouteTmps { get; set; }
        public DbSet<RouteVariant> RouteVariants { get; set; }
        public DbSet<Schedule> Schedules { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TransitService> TransitServices { get; set; }
        public DbSet<TransitSystem> TransitSystems { get; set; }
        public DbSet<TripTemplate> TripTemplates { get; set; }
        public DbSet<TripTemplateStop> TripTemplateStops { get; set; }
    }
}
